### PR TITLE
Skip CUDA installation via a config param.

### PR DESCRIPTION
**Pull request by ktsakalozos**
Should address: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/282

### CODE REVIEW

**Comment by lazypower** [comment]
+1 this LGTM

I think I want @marcoceppi feedback here though as he had some strong opinions in the bug.

**Review by marcoceppi — DISMISSED** [review]
This is phrased odd

**Comment by ktsakalozos** [comment]
I am sorry @marcoceppi in you review i do not see what "phrased odd" refers to.

**Comment by tvansteenburgh** [comment]
I think the changes requested by @marcoceppi are done, so i'm going to dismiss that review and merge this.

**Pull request merged**
